# Generated by Django 6.0.6 on 2026-06-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_user_delete_tbl_login'),
        ('Users', '0002_tbl_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
