# Generated by Django 6.0.6 on 2026-06-24 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_alter_tbl_user_user_photo'),
        ('Users', '0003_alter_tbl_blog_user_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_blog_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.tbl_blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
            options={
                'unique_together': {('user', 'blog')},
            },
        ),
    ]
