# Generated by Django 6.0.6 on 2026-06-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_tbl_blog_like_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_blog_like',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.tbl_blog'),
        ),
    ]
