# Generated by Django 6.0.6 on 2026-06-25 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_tbl_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_blog_comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Users.tbl_blog_comment'),
        ),
    ]
