# Generated by Django 6.0.6 on 2026-06-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_tbl_blog_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
