# Generated by Django 6.0.6 on 2026-06-26 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
        ('Users', '0011_alter_tbl_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_category'),
        ),
    ]
