# Generated by Django 6.0.6 on 2026-06-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_tbl_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_blog',
            name='blog_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
