# Generated by Django 6.0.6 on 2026-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_tbl_blog_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_blog',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
