# Generated by Django 6.0.6 on 2026-06-29 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_user_joined_date'),
        ('Users', '0014_tbl_blog_blog_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_blog_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.tbl_blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
            options={
                'unique_together': {('user', 'blog')},
            },
        ),
    ]
