# Generated by Django 6.0.6 on 2026-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_place', models.CharField(max_length=200)),
                ('user_contact', models.CharField(max_length=10)),
                ('user_gender', models.CharField(max_length=10)),
                ('user_dateofbirth', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_login',
        ),
    ]
