# Generated by Django 6.0.6 on 2026-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_user_delete_tbl_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_photo',
            field=models.ImageField(default='', upload_to='user_images/'),
            preserve_default=False,
        ),
    ]
