# Generated by Django 6.0.6 on 2026-06-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_user_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
