# Generated by Django 6.0.6 on 2026-06-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
